### PR TITLE
Adds P2 handout

### PR DESCRIPTION
**Pull request by anudaweerasinghe**
To Do:
- [x] Finalize timeline / due dates
- [x] Create Gradescope/canvas assignments
- [x] JS/TS decision
- [x] Update teamwork self assessment plan
- [x] Rework points such that [total is 275pts](https://cmu-313.github.io/syllabus/#assessment)
- [x] Setup GitHub classroom

### CODE REVIEW

**Comment by rohanpadhye** [comment]
For 2C: mark both reflections as "Cannot use generative AI"

**Comment by rohanpadhye** [comment]
Weekly teamwork self-assessment: Remove "on canvas"

**Comment by abegel** [comment]
I read all the diffs. I think it's good to go.

**Comment by abegel** [comment]
Looks good to me.

**Pull request merged**
