### PR TITLE
Remaking course website with mkdocs

### PR DESCRIPTION
**Pull request by angelaz1**
Pushing the new version of the website styled with [Material for mkdocs](https://squidfunk.github.io/mkdocs-material/). This format allows for easier sidebar navigation and maintains the previous markdown formatting

Along with the format changes:
- Builds the static website for Fall 2022 and links it to the front page
- Updates README on how to set up local development server & make changes before the semester
- Sets up the base website to be used for Spring 2023
- Removes some duplicate files

image

### CODE REVIEW

**Comment by MichaelHilton** [comment]
overall this looks great.  I wonder if we could move the "overview" stuff that is currently what you see when you load, and focus on a page that is more a landing page/resource page for current students.  Something more like what we see here: https://eecs280.org/

**Comment by angelaz1** [comment]
> overall this looks great. I wonder if we could move the "overview" stuff that is currently what you see when you load, and focus on a page that is more a landing page/resource page for current students. Something more like what we see here: https://eecs280.org/

Sounds great! The above commit moves the overview section to another page & cleans up the weekly schedule markdown to be more readable

I do really like the "week at a glance" in the EECS website, I want to find a way to make that auto-updating. Will be working on a separate branch to set that up + add in all the other course resources

**Comment by angelaz1** [comment]
Added a "This Week" view, common course links, and a Github Action to automatically update the weekly schedule every Sunday

image

**Comment by MichaelHilton** [comment]
overall that looks great! Can you put in the first week of classes/recitation so that there is something there for students to see?  After that, I would be happy to accept

**Comment by angelaz1** [comment]
> overall that looks great! Can you put in the first week of classes/recitation so that there is something there for students to see? After that, I would be happy to accept

Added!

**Comment by MichaelHilton** [comment]
LGTM

**Pull request merged**
