### PR TITLE
Creates P1 Handout

### PR DESCRIPTION
**Pull request by anudaweerasinghe**
[See here for gradescope written assignment](https://www.gradescope.com/courses/583198/assignments/3144258/rubric/edit)

Things that need to be finalized:
- Deadlines and whether we want to create a checkpoint
- How do we want to deal with the old NodeBB repo? 
    - Is closing open issues and PRs enough - this is the easiest option
    - Alternative is to make the old repo private, and create a new repo
- Partial credit for TS translation - this was the biggest pain point last semester

### CODE REVIEW

**Review by rohanpadhye — CHANGES_REQUESTED** [review]
Changes todo:

- Checkpoint on Sep 1
- For each deliverable where the use of AI is not allowed, mention this explicitly (maybe we need a logo or something to mark such questions?). I don't see a "reflection" in the spec here, but if there is one on Gradescope we should mark it as such.
- Criteria for partial credit

**Comment by anudaweerasinghe** [comment]
We don't have any reflections in this assignment, so not marking anything as "AI Forbidden"

Let's add criteria for partial credit depending on how students fare after week 1.

**Comment by abegel** [comment]
In working through P1, I'm doing the GitHub exercise. The GitHub UI around Projects has been changed. The doc: projects/p1/github needs updating to match the new UI. 
1. When you create a project from within the forked repo, it is automatically linked to the repo. There's no need to tell the user to do it manually.
2. When adding a new issue, in addition to assigning it to yourself, the user should also be told to set the Project the issue belongs to (just two fields below Assignees).

Thanks!

**Comment by abegel** [comment]
In the NodeBB installer page for macOS: projects/p1/installation/Mac/
1. After installing redis with brew, you need to start the redis-server like this:
/opt/homebrew/opt/redis/bin/redis-server /opt/homebrew/etc/redis.conf

**Comment by abegel** [comment]
In Project 1B: projects/p1/2_translation/
1. The instruction: "Not be a file that someone else has already picked." is ambiguous. Is that someone on your own team or anyone in the class? Please clarify.

**Comment by rohanpadhye** [comment]
On Mac, I had to also do `npm install typescript` before I could successfully run `./nodebb setup`. Before I did that, I was getting the error:
```
error: uncaughtException: Command failed: npx tsc
```

Do we need to include `typescript` as a dependency in package.json or similar?

**Comment by anudaweerasinghe** [comment]
> On Mac, I had to also do `npm install typescript` before I could successfully run `./nodebb setup`. Before I did that, I was getting the error:
> 
> ```
> error: uncaughtException: Command failed: npx tsc
> ```
> 
> Do we need to include `typescript` as a dependency in package.json or similar?

@rohanpadhye [This PR on the NodeBB repo](https://github.com/CMU-313/NodeBB/pull/1) should fix this.

**Comment by anudaweerasinghe** [comment]
> In the NodeBB installer page for macOS: projects/p1/installation/Mac/
> 
> 1. After installing redis with brew, you need to start the redis-server like this:
>    /opt/homebrew/opt/redis/bin/redis-server /opt/homebrew/etc/redis.conf

Did running `redis-server` directly not work?

**Comment by anudaweerasinghe** [comment]
> In working through P1, I'm doing the GitHub exercise. The GitHub UI around Projects has been changed. The doc: projects/p1/github needs updating to match the new UI.
> 
> 1. When you create a project from within the forked repo, it is automatically linked to the repo. There's no need to tell the user to do it manually.
> 2. When adding a new issue, in addition to assigning it to yourself, the user should also be told to set the Project the issue belongs to (just two fields below Assignees).
> 
> Thanks!

@abegel Since this exercise is the same as our recitation, I updated the [recitation handout](https://cmu-313.github.io/recitations/reci1-github/#activity-2-setting-up-kanban-board-and-creating-issues), moved it to P1B and linked to it instead.

**Review by rohanpadhye — APPROVED** [review]

**Pull request merged**
